spring:
  datasource:
    url: ${DATABASE_CONNECTION:jdbc:mariadb://localhost:3306/test}
    username: ${DATABASE_USER_NAME:test}
    password: ${DATABASE_PASSWORD:test}
    validationQuery: SELECT 1
    testOnBorrow: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ConnectionPool
      leakDetectionThreshold: 5000
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: false
samba:
  video-store-nas:
    url: ${VIDEO_STORE_NAS_URL:smb://localhost:139/alice}
    username: ${VIDEO_STORE_NAS_USERNAME:pinfort}
    password: ${VIDEO_STORE_NAS_PASSWORD:password}
    base-dir: ${VIDEO_STORE_NAS_BASE_DIR:}
  original-store-nas:
    url: ${ORIGINAL_STORE_NAS_URL:smb://localhost:139/bob}
    username: ${ORIGINAL_STORE_NAS_USERNAME:pinfort}
    password: ${ORIGINAL_STORE_NAS_PASSWORD:password}
    base-dir: ${ORIGINAL_STORE_NAS_BASE_DIR:}
processor-tool:
  ts-drop-chk-path: ${TS_DROP_CHK_PATH:C:\tools\tsDropChk\tsDropChkx64.exe}
  ts-splitter-path: ${TS_SPLITTER_PATH:C:\tools\TsSplitter\TsSplitter.exe}
  amatsukaze-add-task-path: ${AMATSUKAZE_ADD_TASK_PATH:C:\tools\Amatsukaze\exe_files\AmatsukazeAddTask.exe}
  ffprobe-path: ${FFPROBE_PATH:ffprobe}
  amatsukaze:
    host: ${AMATSUKAZE_HOST:localhost}
    port: ${AMATSUKAZE_PORT:32768}
    default-profile: ${AMATSUKAZE_DEFAULT_PROFILE:30fps_light}
    atx-div-profile: ${AMATSUKAZE_ATX_DIV_PROFILE:30fps_light_atx_div}
