name: frontend ci
on: 
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'frontend/**'
      - '.github/workflows/ci.frontend.yaml'

defaults:
  run:
    working-directory: frontend

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          version: 11
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: 'frontend/pnpm-lock.yaml'
      - name: install
        run: pnpm install
      - name: typecheck
        run: pnpm typecheck
      - name: build
        run: pnpm build
      - name: lint
        run: pnpm lint
      - name: test
        run: pnpm test
