name: frontend ci
on: 
  pull_request:
    types: [opened, synchronize, reopened]

defaults:
  run:
    working-directory: frontend

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: 'frontend/pnpm-lock.yaml'
      - name: install
        run: pnpm install
      - name: lint
        run: pnpm lint
      #- name: test
      #  run: pnpm test
