name: backend jar generate
on:
  push:
    branches:
      - 'main'

permissions:
  contents: read

defaults:
  run:
    working-directory: backend

jobs:
  gen-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: bootJar
        run: ./gradlew manager:console:bootJar --no-daemon
      - name: upload jar
        uses: actions/upload-artifact@v4
        with:
          name: ts-videos-manager-${{ github.sha }}
          path: backend/manager/console/build/libs/console.jar
          retention-days: 30
